#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

param set EKF2_AID_MASK 24
param set EKF2_EV_DELAY 5
param set EKF2_HGT_MODE 3

param set SIM_GPS_BLOCK 1
